---
# Specifies the location of the log file mysql sends logs to
LogFileLocation: testPath
# Specifies the file where the startup manager will write its PID
PidFile: testPidFile
ChildPidFile: childTestFile
Db:
  # Specifies the user name for MySQL
  User: testUser
  # Specifies the password for connecting to MySQL
  Password:
  PreseededDatabases:
  - DBName: testDbName1
    User: testUser1
    Password:
Manager:
  # Specifies the location to store the statefile for MySQL boot
  StateFileLocation: testStateFileLocation
  # Specifies the job index of the MySQL node
  BootstrapNode: true
  # Comma-delimited list of IPs in the galera cluster
  ClusterIps: ["1.1.1.1", "1.1.1.2", "1.1.1.3"]
  # How many times to attempt database seeding before it fails
  MaxDatabaseSeedTries: 1
  ClusterProbeTimeout: 13
  GaleraInitStatusServerAddress: "127.0.0.1:8999"
